steps:
  #- name: 'copy env file from bucket'
  #  args: ['cp', 'gs://ampersand-env/frontend/.env', './']
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ampersand-group-418009/academics-frontend', '-f', 'academics/Dockerfile', '.']
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ampersand-group-418009/academics-frontend']
  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'academics-frontend'
      - '--image=gcr.io/ampersand-group-418009/academics-frontend'
      - '--platform=managed'
      - '--region=us-central1' 
options:
  logging: CLOUD_LOGGING_ONLY
